# DataSource Config
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://121.196.97.140:3306/db_shiro?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver